---
- name: make contab file
  hosts: test
  tasks: 
    - name: make datejob
      ansible.builtin.cron:
        name: datejob
        minute: 0,30
        weekday: 1,2,3,4,5
        job: date >> /home/ansible/datefile
