---
- name: Configuring Hosts file
  hosts: dev
  tasks: 
    - name: use template module
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/myhosts
        owner: root
        group: root
        mode: '0644'
